name: 'CorePride Institute '
favicon: null
layout_spectrum: 0.37734
typography_spectrum: 0.5265635545365512
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.125
  lightness: 1
  saturation: 0.1875
  rhythmicContrast: 0.25
purpose: []
