name: 'CorePride Institute '
favicon: null
layout_spectrum: 0.8868394626770169
typography_spectrum: 0.5265635545365512
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.9457648538518697
  lightness: 0.10759851499460638
  saturation: 0.10288712871260941
  rhythmicContrast: 0.8614544470328838
purpose: []
